config/routes.rb
Rails.application.routes.draw do
  resources :months
  resources :savings do
  member do
    get 'clone'
    post 'distribute'
    patch 'add_single_month'
    patch 'remove_single_month'
  end
end
  resources :incomes do
    member do
      get 'clone'
      patch 'add_single_month'
      patch 'remove_single_month'
    end
  end
  resources :bills do
    member do
      get 'clone'
      post 'distribute'
      
      patch 'add_single_month'
      patch 'remove_single_month'
    end
  end
  resources :annual_budgets do
    member do
      get 'clone'
    end
  end
  root 'static#index'
end

app/models/annual_budget.rb
class AnnualBudget < ApplicationRecord
  has_many :months, dependent: :destroy
  has_many :incomes, dependent: :destroy
  has_many :savings, dependent: :destroy
  has_many :bills, dependent: :destroy
  validates :name, :year, presence: true
  validates :name, uniqueness: { scope: :year }

  def generate_months
    if self.months.empty?
      (1..12).each do |i|
        self.months.create!(name: Date.new(self.year, i, 1))
      end
    else
      self.errors[:months] << ["Some months already created"]
    end
  end

  def name_as_name_year
    "#{name} #{year}"
  end
end

app/models/saving.rb
class Saving < ApplicationRecord
  belongs_to :annual_budget
  
  has_many :attachments, :as => :attachable, dependent: :destroy
  has_many :months, :through => :attachments
  
  validates :name, :amount, :category, presence: true

  CATEGORIES = [ 'Emergency', 'Fun', 'Retirement', 'College', 'Other' ]
  
  def distribute_across_months
    a = AnnualBudget.find(annual_budget_id)
    a.months.each do |m|
      if m.savings.include?(self)
        next
      else
        m.savings << self
      end
    end
  end
  
  def add_month(month)
    if months.include? month
      errors[:month_ids] << "Month Already Attached"
    else
      months << month
    end
  end
  
end

app/controllers/savings_controller.rb
class SavingsController < ApplicationController
  before_action :set_saving, only: [:show, :edit, :update, :destroy, :distribute, :add_single_month, :remove_single_month]

  # GET /savings
  # GET /savings.json
  def index
    @savings = Saving.all
  end

  # GET /savings/1
  # GET /savings/1.json
  def show
  end

  # GET /savings/new
  def new
    @saving = Saving.new
  end

  # GET /savings/1/edit
  def edit
  end

  # POST /savings
  # POST /savings.json
  def create
    @saving = Saving.new(saving_params)

    respond_to do |format|
      if @saving.save
        format.html { redirect_to edit_saving_path(@saving), notice: 'Saving was successfully created.' }
        format.json { render :show, status: :created, location: @saving }
      else
        format.html { render :new }
        format.json { render json: @saving.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /savings/1
  # PATCH/PUT /savings/1.json
  def update
    respond_to do |format|
      if @saving.update(saving_params)
        format.html { redirect_to edit_saving_path(@saving), notice: 'Saving was successfully updated.' }
        format.json { render :show, status: :ok, location: @saving }
      else
        format.html { render :edit }
        format.json { render json: @saving.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /savings/1
  # DELETE /savings/1.json
  def destroy
    @saving.destroy
    respond_to do |format|
      format.html { redirect_to savings_url, notice: 'Saving was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def clone
    saving = Saving.find(params[:id])
    @saving = saving.dup
    render 'new'
  end
  
  def distribute
    @saving.distribute_item_across_months(@saving)
    redirect_to edit_saving_path(@saving)
  end

  def add_single_month
    params[:saving][:month_ids] = params[:saving][:month_ids].reject(&:empty?)
    #render plain: params[:saving].inspect
    @saving.add_month_to_item(Month.find(params[:saving][:month_ids]), @saving)
    redirect_to edit_saving_path(@saving)
  end
  
  def remove_single_month
#     render plain: params[:saving].inspect
    @saving.months.destroy(params[:saving][:month_ids])
    redirect_to edit_saving_path(@saving)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saving
      @saving = Saving.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saving_params
      params.require(:saving).permit(:category, :amount, :name, :recurring, :save_date, :annual_budget_id, :month_ids => [])
    end
end

app/helpers/savings_helper.rb
module SavingsHelper
end

app/views/savings/_attachment_form.html.erb
<div class="cell small-6 large-2"> 

              <% if @saving.months.length < 12 %>
	                      <%= form_with(model: @saving, local: true, url: { action: 'add_single_month' }) do |form| %>
	                        <% if @saving.errors.any? %>
	                          <div id="error_explanation">
                    <h2><%= pluralize(@saving.errors.count, "error") %> prohibited this Saving from being saved:</h2>

		                              <ul>
		                                <% @saving.errors.full_messages.each do |message| %>
			                                          <li><%= message %></li>
		                                <% end %>
		                              </ul>
		                            </div>
		                          <% end %>

<div class="field">
	<%= form.label 'Attach to month:' %>
	<ul style="list-style: none;">
<%#= form.collection_select(:month_ids, Month.where(annual_budget_id: @saving.annual_budget_id) - @saving.months, :id, :name_as_month_year) %>
<%= form.collection_check_boxes :month_ids, (Month.where(annual_budget_id: @saving.annual_budget_id) - @saving.months).sort, :id, :name_as_month_year do |b| %>
	<li>
	<%= b.check_box %>
	<%= b.label %>
	</li>
<% end %>
	</ul>
	
				           </div>

					<div class="actions">
					<%= form.submit 'Attach' %>
					</div>
			<% end %>
		<% end %>


<hr>
<p>
<strong>Attached Months:</strong><br>
<ul style="list-style: none;">
	<% @saving.months.sort.each do |m| %>
		<li>
	<%= m.name_as_month_year %>
	</li>
<% end %>
</p>


<% if @saving.months.length < 12 %>
<p>OR:</p>
<%= button_to('Add to all months in attached budget', action: 'distribute') %>
<% end %>

<hr>

<% if @saving.months.length > 0 %>
<%= form_with(model: @saving, local:true, url: { action: 'remove_single_month' }) do |form| %>
<% if @saving.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@saving.errors.count, "error") %> prohibited this month from being removed:</h2>

<ul>
<% @saving.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
</ul>
</div>
<% end %>
<div class="field">
<%= form.label 'Remove from month:' %>
<%= form.collection_select(:month_ids, @saving.months.sort, :id, :name_as_month_year) %>
</div>

<div class="actions">
<%= form.submit 'Remove' %>
</div>
<% end %>
<% end %>


</div>

app/views/savings/_form.html.erb
  <div class="cell small-8 large-2" style="text-align: center;">

<%= form_with(model: saving, local: true) do |form| %>
  <% if saving.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(saving.errors.count, "error") %> prohibited this saving from being saved:</h2>

      <ul>
        <% saving.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <div class="field">
        <%= form.label :name %>
          <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :amount %>
	<%= form.number_field :amount, :step => 0.01 %>
      </div>

      <div class="field">
        <%= form.label :category %>
          <%= form.select :category, options_for_select(Saving::CATEGORIES, saving.category) %>
      </div>

      <div class="field">
        <%= form.label :annual_budget_id %>
          <%= form.collection_select(:annual_budget_id, AnnualBudget.all, :id, :name) %>
      </div>

      <div class="actions">
        <%= form.submit "Update", { class: "button", style: "color: white;" } %>
      </div>
      <% end %>
</div>

app/views/savings/edit.html.erb
<div class="grid-x grid-margin-x align-center">
  <div class="cell" style="text-align: center;">
<h1>Editing Saving</h1>
  </div>
<%= render 'form', saving: @saving %>
<%= render 'attachment_form', saving: @saving %>
  <div class="cell" style="text-align: center;">

<%= link_to 'Back', savings_path, { class: "button", style: "color: white;" } %>
</div>
</div>

app/views/savings/index.html.erb
<p id="notice"><%= notice %></p>
<div class="grid-x align-center">
  <div class="cell" style="text-align: center;">
<h1>Savings</h1>
  </div>
  <div class="cell small-6" style="text-align: center;">
  
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>Type</th>
      <th>Budget</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @savings.order(:save_date).each do |saving| %>
      <tr>
        <td><%= saving.name %></td>
        <td>$<%= '%.2f' % saving.amount %></td>
        <td><%= saving.category %></td>
        <td><%= link_to "#{saving.annual_budget.name}", annual_budget_path(saving.annual_budget_id) %></td>
        <td><%= link_to 'Edit', edit_saving_path(saving) %></td>
        <td><%= link_to 'Destroy', saving, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
<br>
  <div class="cell" style="text-align: center;">

<%= link_to 'New Saving', new_saving_path, { class: "button", style: "color: white;" } %>
  </div>
</div>

app/views/savings/new.html.erb
<div class="grid-x align-center">
  <div class="cell" style="text-align: center;">
<h1>New Saving</h1>
  </div>
<%= render 'form', saving: @saving %>
  <div class="cell" style="text-align: center;">

<%= link_to 'Back', savings_path, { class: "button", style: "color: white;" } %>
  </div>
</div>

app/views/savings/show.html.erb
<p id="notice"><%= notice %></p>
<div class="grid-x align-center">
  <div class="cell small-6" style="text-align: center;">
<p>
  <strong>Name:</strong><br>
  <%= @saving.name %>
</p>

<p>
  <strong>Amount:</strong><br>
  <%= @saving.amount %>
</p>

<p>
  <strong>Category:</strong><br>
  <%= @saving.category %>
</p>

<p>
  <strong>Attached to Budget:</strong><br>
<%= link_to "#{@saving.annual_budget.name}", annual_budget_path(@saving.annual_budget_id), { class: "button", style: "color: white;" } %>
</p>

<p>
  <strong>Attached Months:</strong><br>
  <% @saving.months.each do |m| %>
  <% if m == @saving.months.last %>
        <%= m.name_as_month_year %>
      <% else %>
        <%= m.name_as_month_year %> | 
      <% end %>
  <% end %>
</p>
    
    <hr>
   
<% if @saving.months.length < 12 %>
<%= form_with(model: @saving, local: true, url: { action: 'add_single_month' }) do |form| %>
  <% if @saving.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saving.errors.count, "error") %> prohibited this Saving from being saved:</h2>

      <ul>
        <% @saving.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= form.label 'Attach to month:' %>
  <%= form.collection_select(:month_ids, Month.where(annual_budget_id: @saving.annual_budget_id) - @saving.months, :id, :name_as_month_year) %>
</div>

  <div class="actions">
    <%= form.submit 'Attach' %>
  </div>
<% end %>
<% end %>

<% if @saving.months.length < 12 %>
  <p>OR:</p>
  <%= button_to('Add to all months in attached budget', action: 'distribute') %>
<% end %>

    <hr>
    
<% if @saving.months.length > 0 %>
<%= form_with(model: @saving, local:true, url: { action: 'remove_single_month' }) do |form| %>
  <% if @saving.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saving.errors.count, "error") %> prohibited this month from being removed:</h2>
      
      <ul>
        <% @saving.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
  <%= form.label 'Remove from month:' %>
  <%= form.collection_select(:month_ids, @saving.months, :id, :name_as_month_year) %>
</div>

  <div class="actions">
    <%= form.submit 'Remove' %>
  </div>
<% end %>
<% end %>

    <hr>
      <div class="cell" style="text-align: center;">

<%= link_to 'Edit', edit_saving_path(@saving), { class: "button", style: "color: white;" } %> |
<%= link_to 'Clone', clone_saving_path(@saving), { class: "button", style: "color: white;" } %> |
<%= link_to 'Back', savings_path, { class: "button", style: "color: white;" } %>
  </div>
</div>