config/routes.rb
Rails.application.routes.draw do
  resources :months
  resources :savings do
  member do
    get 'clone'
    post 'distribute'
    patch 'add_single_month'
    patch 'remove_single_month'
  end
end
  resources :incomes do
    member do
      get 'clone'
      patch 'add_single_month'
      patch 'remove_single_month'
    end
  end
  resources :bills do
    member do
      get 'clone'
      post 'distribute'
      
      patch 'add_single_month'
      patch 'remove_single_month'
    end
  end
  resources :annual_budgets do
    member do
      get 'clone'
    end
  end
  root 'static#index'
end

app/models/annual_budget.rb
class AnnualBudget < ApplicationRecord
  has_many :months, dependent: :destroy
  has_many :incomes, dependent: :destroy
  has_many :savings, dependent: :destroy
  has_many :bills, dependent: :destroy
  validates :name, :year, presence: true
  validates :name, uniqueness: { scope: :year }

  def generate_months
    if self.months.empty?
      (1..12).each do |i|
        self.months.create!(name: Date.new(self.year, i, 1))
      end
    else
      self.errors[:months] << ["Some months already created"]
    end
  end

  def name_as_name_year
    "#{name} #{year}"
  end
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :annual_budget
  
  has_many :attachments, :as => :attachable, dependent: :destroy
  has_many :months, :through => :attachments

  validates :name, :withdrawal_date,
            :amount, presence: true

  def distribute_across_months
    a = AnnualBudget.find(annual_budget_id)
    a.months.each do |m|
      if m.bills.include?(self)
        next
      else
        m.bills << self
      end
    end
  end

  def add_month(month)
    if months.include? month
      errors[:month_ids] << "Month Already Attached"
    else
      months << month
    end
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy, :distribute, :add_single_month, :remove_single_month]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    # render plain: params[:bill].inspect
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to edit_bill_path(@bill), notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to edit_bill_path(@bill), notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def clone
    bill = Bill.find(params[:id])
    @bill = bill.dup
    render 'new'
  end

  def distribute
    @bill.distribute_item_across_months(@bill)
    redirect_to edit_bill_path(@bill)
  end

  def add_single_month
    # render plain: params[:bill].inspect
    params[:bill][:month_ids] = params[:bill][:month_ids].reject(&:empty?)
    @bill.add_month_to_item(Month.find(params[:bill][:month_ids]), @bill)
    redirect_to edit_bill_path(@bill)
  end
  
  def remove_single_month
#     render plain: params[:bill].inspect
    @bill.months.destroy(params[:bill][:month_ids])
    redirect_to edit_bill_path(@bill)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:start_date, :end_date, :withdrawal_date, :amount, :name, :recurring, :annual_budget_id, :month_ids => [])
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_attachment_form.html.erb
<div class="cell small-6 large-2"> 

              <% if @bill.months.length < 12 %>
	                      <%= form_with(model: @bill, local: true, url: { action: 'add_single_month' }) do |form| %>
	                        <% if @bill.errors.any? %>
	                          <div id="error_explanation">
                    <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

		                              <ul>
		                                <% @bill.errors.full_messages.each do |message| %>
			                                          <li><%= message %></li>
		                                <% end %>
		                              </ul>
		                            </div>
		                          <% end %>

<div class="field">
	<%= form.label 'Attach to month:' %>
	<ul style="list-style: none;">
<%= form.collection_check_boxes :month_ids, (Month.where(annual_budget_id: @bill.annual_budget_id) - @bill.months).sort, :id, :name_as_month_year do |b| %>
	<li>
	<%= b.check_box %>
	<%= b.label %>
	</li>
<% end %>
</ul>
					   </div>

					<div class="actions">
					<%= form.submit 'Attach' %>
					</div>
			<% end %>
		<% end %>


<hr>
<p>
<strong>Attached Months:</strong><br>
<ul style="list-style: none;">
<% @bill.months.sort.each do |m| %>
<li>
<%= m.name_as_month_year %>
</li>
<% end %>
</p>


<% if @bill.months.length < 12 %>
<p>OR:</p>
<%= button_to('Add to all months in attached budget', action: 'distribute') %>
<% end %>

<hr>

<% if @bill.months.length > 0 %>
<%= form_with(model: @bill, local:true, url: { action: 'remove_single_month' }) do |form| %>
<% if @bill.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@bill.errors.count, "error") %> prohibited this month from being removed:</h2>

<ul>
<% @bill.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
</ul>
</div>
<% end %>
<div class="field">
<%= form.label 'Remove from month:' %>
<%= form.collection_select(:month_ids, @bill.months.sort, :id, :name_as_month_year) %>
</div>

<div class="actions">
<%= form.submit 'Remove' %>
</div>
<% end %>
<% end %>


</div>

app/views/bills/_form.html.erb
<div class="cell small-8 large-2" style="text-align: center;">
  <%= form_with(model: bill, local: true) do |form| %>
    <% if bill.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>
        <ul>
        <% bill.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :amount %>
      <%= form.number_field :amount, :step => 0.01 %>
    </div>

    <div class="field">
      <%= form.label :withdrawal_date %>
      <%= form.date_select :withdrawal_date, order: [ :day, :month, :year ] %>
    </div>

    <div class="field">
      <%= form.label 'Attach to budget:' %>
      <%= form.collection_select(:annual_budget_id, AnnualBudget.all, :id, :name_as_name_year) %>
    </div>

    <div class="actions">
      <%= form.submit "Update", { class: "button", style: "color: white;" } %>
    </div>
  <% end %>
</div>

app/views/bills/edit.html.erb
<p id="notice">
<%= notice %>
</p>
<div class="grid-x grid-margin-x align-center">
  <div class="cell" style="text-align: center;">
    <h1>Editing Bill</h1>
  </div>
  <%= render 'form', bill: @bill %>
  <%= render 'attachment_form', bill: @bill %>
  <div class="cell" style="text-align: center;">
    <%= link_to 'Back', bills_path, { class: "button", style: "color: white;" } %>
  </div>
</div>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>
<div class="grid-x align-center">
  <div class="cell" style="text-align: center;">
<h1>Bills</h1>
  </div>
  <div class="cell small-6">
    <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Withdrawal date</th>
      <th>Amount</th>
      <th>Budget</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.name %></td>
        <td><%= bill.withdrawal_date %></td>
        <td>$<%= '%.2f' % bill.amount %></td>
        <td><%= link_to "#{bill.annual_budget.name}", annual_budget_path(bill.annual_budget_id) %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Delete', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>


<br>
  <div class="cell" style="text-align: center;">
<%= link_to 'New Bill', new_bill_path, { class: "button", style: "color: white" } %>
  </div>
</div>

app/views/bills/new.html.erb
<div class="grid-x align-center">
  <div class="cell" style="text-align: center;">
    <h1>New Bill</h1>
  </div>

  <%= render 'form', bill: @bill %>
  
<div class="cell" style="text-align: center;">
  <%= link_to 'Back', bills_path, { class: "button", style: "color: white;" } %>
</div>
</div>

app/views/bills/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<div class="grid-x align-center">
  <div class="cell small-6">
    <p>
      <strong>Name:</strong><br>
      <%= @bill.name %>
    </p>

    <p>
      <strong>Amount:</strong><br> $
      <%= '%.2f' % @bill.amount %>
    </p>

    <p>
      <strong>Withdrawal date:</strong><br>
      <%= @bill.withdrawal_date.strftime("#{@bill.withdrawal_date.day.ordinalize}") %>
    </p>

    <p>
      <strong>In this Budget:</strong><br>
      <%= link_to "#{@bill.annual_budget.name}", annual_budget_path(@bill.annual_budget_id), { class: "button", style: "color: white" } %>
    </p>

    <p>
      <strong>In these Months:</strong><br>
      <% @bill.months.each do |m| %>
        <% if m == @bill.months.last %>
          <%= m.name_as_month_year %>
            <% else %>
              <%= m.name_as_month_year %> |
                <% end %>
                  <% end %>
    </p>

    <hr>

    <% if @bill.months.length < 12 %>
      <%= form_with(model: @bill, local: true, url: { action: 'add_single_month' }) do |form| %>
        <% if @bill.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

            <ul>
              <% @bill.errors.full_messages.each do |message| %>
                <li>
                  <%= message %>
                </li>
                <% end %>
            </ul>
          </div>
          <% end %>

            <div class="field">
              <%= form.label 'Attach to month:' %>
                <%= form.collection_select(:month_ids, Month.where(annual_budget_id: @bill.annual_budget_id) - @bill.months, :id, :name_as_month_year) %>
            </div>

            <div class="actions">
              <%= form.submit "Attach" %>
            </div>
            <% end %>
              <% end %>

                <% if @bill.months.length < 12 %>
                  <p>OR:</p>
                  <%= button_to('Add to all months in this budget', { action: 'distribute' }) %>
                    <% end %>
                      <hr>
                      <% if @bill.months.length > 0 %>
                        <%= form_with(model: @bill, local:true, url: { action: 'remove_single_month' }) do |form| %>
                          <% if @bill.errors.any? %>
                            <div id="error_explanation">
                              <h2>
                                <%= pluralize(@bill.errors.count, "error") %> prohibited this month from being removed:</h2>

                              <ul>
                                <% @bill.errors.full_messages.each do |message| %>
                                  <li>
                                    <%= message %>
                                  </li>
                                  <% end %>
                              </ul>
                            </div>
                            <% end %>
                              <div class="field">
                                <%= form.label 'Remove from month:' %>
                                  <%= form.collection_select(:month_ids, @bill.months, :id, :name_as_month_year) %>
                              </div>

                              <div class="actions">
                                <%= form.submit "Remove" %>
                              </div>
                              <% end %>
                                <% end %>
  <hr>
  </div>


  <div class="cell" style="text-align: center;">
    <%= link_to 'Edit', edit_bill_path(@bill), { class: "button", style: "color: white" } %> |
      <%= link_to 'Clone', clone_bill_path(@bill), { class: "button", style: "color: white" } %> |
        <%= link_to 'Back', bills_path, { class: "button", style: "color: white" } %>
  </div>
</div>