config/routes.rb
Rails.application.routes.draw do
  resources :months
  resources :savings do
  member do
    get 'clone'
    post 'distribute'
    patch 'add_single_month'
    patch 'remove_single_month'
  end
end
  resources :incomes do
    member do
      get 'clone'
      patch 'add_single_month'
      patch 'remove_single_month'
    end
  end
  resources :bills do
    member do
      get 'clone'
      post 'distribute'
      
      patch 'add_single_month'
      patch 'remove_single_month'
    end
  end
  resources :annual_budgets do
    member do
      get 'clone'
    end
  end
  root 'static#index'
end

app/models/annual_budget.rb
class AnnualBudget < ApplicationRecord
  has_many :months, dependent: :destroy
  has_many :incomes, dependent: :destroy
  has_many :savings, dependent: :destroy
  has_many :bills, dependent: :destroy
  validates :name, :year, presence: true
  validates :name, uniqueness: { scope: :year }

  def generate_months
    if self.months.empty?
      (1..12).each do |i|
        self.months.create!(name: Date.new(self.year, i, 1))
      end
    else
      self.errors[:months] << ["Some months already created"]
    end
  end

  def name_as_name_year
    "#{name} #{year}"
  end
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :annual_budget
  
  has_many :attachments, :as => :attachable, dependent: :destroy
  has_many :months, :through => :attachments
  
  validates :source, :pay_date, :gross_amount,
            :federal_tax, :state_tax,
            :social_sec_tax, :medicare_tax, presence: true

  before_save :set_net_income
  before_update :set_net_income


  def set_net_income
    self.net_amount = '%.2f' % (gross_amount - federal_tax - state_tax - medicare_tax - social_sec_tax)
  end

  def available_months
      AnnualBudget.find(annual_budget_id).months
  end
  
  def add_month(month)
    if months.include? month
      errors[:month_ids] << "Month Already Attached"
    else
      months << month
    end
  end
  
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy, :add_single_month, :remove_single_month]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all

  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to edit_income_path(@income), notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to edit_income_path(@income), notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def clone
    income = Income.find(params[:id])
    @income = income.dup
    render 'new'
  end

  def add_single_month
    # render plain: params[:bill].inspect
    params[:income][:month_ids] = params[:income][:month_ids].reject(&:empty?)
    @income.add_month_to_item(Month.find(params[:income][:month_ids]), @income)
    redirect_to edit_income_path(@income)
  end
  
  def remove_single_month
#     render plain: params[:income].inspect
    @income.months.destroy(params[:income][:month_ids])
    redirect_to edit_income_path(@income)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
  def set_income 
    @income = Income.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def income_params
    params.require(:income).permit(:source, :pay_date, :gross_amount, :use_month, :start_date, :end_date, :recurring, :federal_tax, :state_tax, :social_sec_tax, :medicare_tax, :net_amount, :annual_budget_id, :month_ids => [])
  end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_attachment_form.html.erb
<div class="cell small-6 large-2"> 

              <% if @income.months.length < 12 %>
	                      <%= form_with(model: @income, local: true, url: { action: 'add_single_month' }) do |form| %>
	                        <% if @income.errors.any? %>
	                          <div id="error_explanation">
                    <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

		                              <ul>
		                                <% @income.errors.full_messages.each do |message| %>
			                                          <li><%= message %></li>
		                                <% end %>
		                              </ul>
		                            </div>
		                          <% end %>

<div class="field">
	<%= form.label 'Attach to month:' %>
	<ul style="list-style: none;">
<%= form.collection_check_boxes:month_ids, (Month.where(annual_budget_id: @income.annual_budget_id) - @income.months).sort, :id, :name_as_month_year do |b| %>
	<li>
	<%= b.check_box %>
	<%= b.label %>
	</li>
	<% end %>
	</ul>

</div>

					<div class="actions">
					<%= form.submit 'Attach' %>
					</div>
			<% end %>
		<% end %>


<hr>
<p>
<strong>Attached Months:</strong><br>
<ul style="list-style: none;">
	<% @income.months.sort.each do |m| %>
		<li>
	<%= m.name_as_month_year %>
	</li>
<% end %>
</p>


<hr>

<% if @income.months.length > 0 %>
<%= form_with(model: @income, local:true, url: { action: 'remove_single_month' }) do |form| %>
<% if @income.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@income.errors.count, "error") %> prohibited this month from being removed:</h2>

<ul>
<% @income.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
</ul>
</div>
<% end %>
<div class="field">
<%= form.label 'Remove from month:' %>
<%= form.collection_select(:month_ids, @income.months.sort, :id, :name_as_month_year) %>
</div>

<div class="actions">
<%= form.submit 'Remove' %>
</div>
<% end %>
<% end %>


</div>

app/views/incomes/_form.html.erb
  <div class="cell small-8 large-2" style="text-align: center;">

<%= form_with(model: income, local: true) do |form| %>
  <% if income.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
        <% income.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <div class="field">
        <%= form.label :source %>
          <%= form.text_field :source %>
      </div>

      <div class="field">
        <%= form.label :pay_date %>
          <%= form.date_select :pay_date, :discard_year => true %>
      </div>

      <div class="field">
        <%= form.label :gross_amount %>
          <%= form.number_field :gross_amount, :step => 0.01 %>
      </div>

      <div class="field">
        <%= form.label :federal_tax %>
          <%= form.number_field :federal_tax, :step => 0.01 %>
      </div>

      <div class="field">
        <%= form.label :state_tax %>
          <%= form.number_field :state_tax, :step => 0.01 %>
      </div>

      <div class="field">
        <%= form.label :social_sec_tax %>
          <%= form.number_field :social_sec_tax, :step => 0.01 %>
      </div>

      <div class="field">
        <%= form.label :medicare_tax %>
          <%= form.number_field :medicare_tax, :step => 0.01 %>
      </div>

      <div class="field">
        <%= form.label :annual_budget_id %>
          <%= form.collection_select(:annual_budget_id, AnnualBudget.all, :id, :name_as_name_year) %>
      </div>

      <div class="actions">
        <%= form.submit "Update", { class: "button", style: "color: white;" } %>
      </div>
      <% end %>
</div>

app/views/incomes/edit.html.erb
<p id="notice">
<%= notice %>
</p>

<div class="grid-x grid-margin-x align-center">

<div class="cell" style="text-align: center;">
<h1>Editing Income</h1>
</div>
<%= render 'form', income: @income %>
<%= render 'attachment_form', income: @income %>
  <div class="cell" style="text-align: center;">
<%= link_to 'Back', incomes_path, { class: "button", style: "color: white;" }%>
</div>
</div>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="grid-x align-center">
  <div class="cell" style="text-align: center;">
<h1>Incomes</h1>
  </div>
  <div class="cell small-10" style="text-align: center;">
<table>
  <thead>
  <tr>
    <th>Source</th>
    <th>Pay Date</th>
    <th>Gross Amount</th>
    <th>Federal Tax</th>
    <th>State Tax</th>
    <th>Social Security Tax</th>
    <th>Medicare Tax</th>
    <th>Net Amount</th>
    <th>Budget</th>
    <th colspan="2">Actions</th>
  </tr>
  </thead>

  <tbody>
         <% @incomes.order(:pay_date, :source).each do |income| %>
      <tr>
        <td><%= income.source %></td>
        <td><%= income.pay_date %></td>
        <td>$<%= '%.2f' % income.gross_amount %></td>
        <td>$<%= '%.2f' % income.federal_tax %></td>
        <td>$<%= '%.2f' % income.state_tax %></td>
        <td>$<%= '%.2f' % income.social_sec_tax %></td>
        <td>$<%= '%.2f' % income.medicare_tax %></td>
        <td>$<%= '%.2f' % income.net_amount %></td>
        <td><%= link_to "#{income.annual_budget.name}", annual_budget_path(income.annual_budget_id) %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Delete', income, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  </div>
  <div class="cell" style="text-align: center;">
<%= link_to 'New Income', new_income_path, { class: "button", style: "color: white;" } %>
  </div>
</div>

app/views/incomes/new.html.erb
<div class="grid-x align-center">
  <div class="cell" style="text-align: center;">
    <h1>New Income</h1>
  </div>
  <%= render 'form', income: @income %>
    <div class="cell" style="text-align: center;">
      <%= link_to 'Back', incomes_path %>
    </div>
</div>

app/views/incomes/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<div class="grid-x align-center">
  <div class="cell small-6" style="text-align: center;">
    <p>
      <strong>Source:</strong><br>
      <%= @income.source %>
    </p>

    <p>
      <strong>Pay date:</strong><br>
      <%= @income.pay_date.strftime("%B #{@income.pay_date.day.ordinalize}") %>
    </p>

    <p>
      <strong>Gross:</strong><br>
      <%= '%.2f' % @income.gross_amount %>
    </p>

    <p>
      <strong>Federal tax:</strong><br>
      <%= '%.2f' % @income.federal_tax %>
    </p>

    <p>
      <strong>State tax:</strong><br>
      <%= '%.2f' % @income.state_tax %>
    </p>

    <p>
      <strong>Social sec tax:</strong><br>
      <%= '%.2f' % @income.social_sec_tax %>
    </p>

    <p>
      <strong>Medicare tax:</strong><br>
      <%= '%.2f' % @income.medicare_tax %>
    </p>

    <p>
      <strong>Net:</strong><br>
      <%= '%.2f' % @income.net_amount %>
    </p>

    <p>
      <strong>Attached to Budget:</strong><br>
      <%= link_to "#{@income.annual_budget.name}", annual_budget_path(@income.annual_budget_id), { class: "button", style: "color: white;" } %>
    </p>

    <p>
      <strong>Attached Months:</strong><br>
      <% @income.months.each do |i| %>
        <%= i.name_as_month_year %>
          <% end %>
    </p>
    <hr>
    <% if @income.months.length < 12 %>
      <%= form_with(model: @income, local: true, url: { action: 'add_single_month' }) do |form| %>
        <% if @income.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@income.errors.count, "error") %> prohibited this month from being added:</h2>

            <ul>
              <% @income.errors.full_messages.each do |message| %>
                <li>
                  <%= message %>
                </li>
                <% end %>
            </ul>
          </div>
          <% end %>

            <div class="field">
              <%= form.label 'Attach to Month:' %>
                <%= form.collection_select(:month_ids, Month.where(annual_budget_id: @income.annual_budget_id) - @income.months, :id, :name_as_month_year) %>
            </div>

            <div class="actions">
              <%= form.submit 'Attach' %>
            </div>
            <% end %>
              <% end %>

                <hr>
                <% if @income.months.length > 0 %>
                  <%= form_with(model: @income, local:true, url: { action: 'remove_single_month' }) do |form| %>
                    <% if @income.errors.any? %>
                      <div id="error_explanation">
                        <h2>
                          <%= pluralize(@income.errors.count, "error") %> prohibited this month from being removed:</h2>

                        <ul>
                          <% @income.errors.full_messages.each do |message| %>
                            <li>
                              <%= message %>
                            </li>
                            <% end %>
                        </ul>
                      </div>
                      <% end %>
                        <div class="field">
                          <%= form.label 'Remove from Month:' %>
                            <%= form.collection_select(:month_ids, @income.months, :id, :name_as_month_year) %>
                        </div>

                        <div class="actions">
                          <%= form.submit 'Remove' %>
                        </div>
                        <% end %>
                          <% end %>
    <hr>
  </div>

  <div class="cell" style="text-align: center;">
    <%= link_to 'Edit', edit_income_path(@income), { class: "button", style: "color: white;" } %> |
      <%= link_to 'Clone', clone_income_path(@income), { class: "button", style: "color: white;" } %> |
        <%= link_to 'Back', incomes_path, { class: "button", style: "color: white;" } %>
  </div>
</div>