config/routes.rb
Rails.application.routes.draw do
  resources :months
  resources :savings do
  member do
    get 'clone'
    post 'distribute'
    patch 'add_single_month'
    patch 'remove_single_month'
  end
end
  resources :incomes do
    member do
      get 'clone'
      patch 'add_single_month'
      patch 'remove_single_month'
    end
  end
  resources :bills do
    member do
      get 'clone'
      post 'distribute'
      
      patch 'add_single_month'
      patch 'remove_single_month'
    end
  end
  resources :annual_budgets do
    member do
      get 'clone'
    end
  end
  root 'static#index'
end

app/views/layouts/_bills.html.erb
<% if month.bills.empty? %>
<h3>
  No Bills For This Month
</h3>
<% else %>
<div class="table-scroll grid-x align-center">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Day</th>
      <th>Amount</th>
      <th>Percent</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% month.bills.order(:withdrawal_date).each do |bill| %>
        <tr>
          <td>
            <%= bill.name %>
          </td>
          <td>
            <%= bill.withdrawal_date.day %>
          </td>
          <td>
            <%= '%.2f' % bill.amount %>
          </td>
          <td>
            <%= get_single_percentage(month, bill.amount) %>
          </td>
          <td>
            <%= link_to 'Edit', edit_bill_path(bill) %>
          </td>
          <td>
            <%= link_to 'Destroy', bill, method: :delete, data: {confirm: 'Are you sure?'} %>
          </td>

        </tr>
        <% end %>
            <tr>
              <th>TOTAL:</th>
              <th></th>
              <th><%= '%.2f' % month.bills.sum(&:amount) %></th>
              <th><%= get_total_percentage(month, 'bills') %></th>
	      <th><%= link_to 'Add', new_bill_path %></th>
	      <th><%= link_to 'See All', bills_path %></th>
            </tr>
  </tbody>
</table>
</div>
<% end %>
<div class="grid-x align-center grid-margin-x" style="text-align: center;">
  <div class="cell small-3">
    <%= link_to "Add A Bill", new_bill_path, {class: "button small", style: "color: white;"} %>
  </div>
  <div class="cell small-3">
    <%= link_to "See All Bills`", bills_path, {class: "button small", style: "color: white;"} %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="top-bar" style="position: absolute; width: 100%; bottom: 0;">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>Thanks for using Easy Budget</li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li>
        Copyright RH: <%= Date.today.strftime("%Y") %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_incomes.html.erb
<% if month.incomes.empty? %>
<h3>
  No Incomes For This Month
</h3>
<% else %>
<div class="table-scroll grid-x align-center">
<table>
  <thead>
    <tr>
      <th>Pay Date</th>
      <th>Source</th>
      <th>Gross Pay</th>
      <th>Net Pay</th>
      <th>Percent of Net</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% month.incomes.order(:source).each do |income| %>
      <tr>
        <td><%= income.pay_date.strftime("%d %B") %></td>
        <td><%= income.source %></td>
        <td><%= '%.2f' % income.gross_amount %></td>
        <td><%= '%.2f' % income.net_amount %></td>
        <td><%= get_single_percentage(month, income.net_amount) %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Delete', income, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
        <% end %>
    <tr>
      <th>TOTAL:</th>
      <th></th>
      <th><%= '%.2f' % month.incomes.sum(&:gross_amount) %></th>
      <th><%= '%.2f' % month.incomes.sum(&:net_amount) %></th>
      <th><%= get_total_percentage(month, 'incomes') %></th>
      <th><%= link_to 'Add', new_income_path %></th>
      <th colspan="2"><%= link_to 'See All', incomes_path %></th>
    </tr>
  </tbody>
</table>
</div>
<% end %>
<div class="grid-x align-center grid-margin-x" style="text-align: center;">
  <div class="cell small-3">
    <%= link_to 'Add An Income', new_income_path, {class: "button small", style: "color: white;"} %>
  </div>
  <div class="cell small-3">
    <%= link_to 'See All Incomes', incomes_path, {class: "button small", style: "color: white;"} %>
  </div>
</div>

app/views/layouts/_leftovers.html.erb
<% if month.get_leftovers == 0 %>
<h3>
  Nothing left this month.
</h3>
<% elsif month.get_leftovers < 0 %>
  <h3 style="color: red;">
    You are in the hole $<%= '%.2f' % month.get_leftovers.abs %>!!
  </h3>
  <% else %>
  <h3>
    You have $<%= '%.2f' % month.get_leftovers %> left.
  </h3>
  <h5>
    Maybe you should save it >>>>>  <%= link_to 'Save it', new_saving_path, {class: "button small", style: "color: white;"} %>
  </h5>
<% end %>

app/views/layouts/_months.html.erb
<div class="grid-x align-center">
  <div class="cell small-9">
    <ul class="accordion" data-accordion data-allow-all-closed="true" data-multi-expand="true">
      <% @annual_budget.months.order(:name).each do |month| %>
        <li class="accordion-item" data-accordion-item>
          <!-- Accordion tab title -->
          <a href="#" class="accordion-title" style="background-color: lightgray; border-color: black;"><%= month.name.strftime("%B %y") %></a>
          <!-- Accordion tab content: it would start in the open state due to using the `is-active` state class. -->
          <div class="accordion-content" data-tab-content>
            <ul class="tabs" data-tabs id="<%= month.name %>">
              <li class="tabs-title is-active"><a href="#<%= month.name %>incomes" aria-selected="true">Income</a></li>
              <li class="tabs-title"><a data-tabs-target="<%= month.name %>bills" href="#<%= month.name %>bills">Bills</a></li>
              <li class="tabs-title"><a data-tabs-target="<%= month.name %>savings" href="#<%= month.name %>savings">Savings</a></li>
              <li class="tabs-title"><a data-tabs-target="<%= month.name %>spending" href="#<%= month.name %>leftover">Spending</a></li>
              <li class="tabs-title"><a data-tabs-target="<%= month.name %>leftover" href="#<%= month.name %>leftover">Leftover</a></li>
            </ul>

            <div class="tabs-content" data-tabs-content="<%= month.name %>">
              <div class="tabs-panel is-active" id="<%= month.name %>incomes">
                <%= render 'layouts/incomes', month: month %>

              </div>
              <div class="tabs-panel" id="<%= month.name %>bills">
                <%= render 'layouts/bills', month: month %>
              </div>
              <div class="tabs-panel" id="<%= month.name %>savings">
                <%= render 'layouts/savings', month: month %>
              </div>
              <div class="tabs-panel" id="<%= month.name %>spending">
                <%= render 'layouts/spendings', month:month %>
              </div>
              <div class="tabs-panel" id="<%= month.name %>leftover">
                <%= render 'layouts/leftovers', month:month %>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="title-bar" data-responsive-toggle="top-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="top-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li><%= link_to "Easy Budget", root_path %></li>
    </ul>
  </div>
  <div class="top-bar-right" id="top-menu">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <%= link_to "Budgets", annual_budgets_path %>
        <ul class="menu vertical">
          <li><%= link_to "Create", new_annual_budget_path %></li>
          <li><%= link_to "All Budgets", annual_budgets_path %></li>
        </ul>
      </li>
      <li>
        <%= link_to "Incomes", incomes_path %>
        <ul class="menu vertical">
          <li><%= link_to "Create", new_income_path %></li>
          <li><%= link_to "All Incomes", incomes_path %></li>
        </ul>
      </li>
      <li>
        <%= link_to "Bills", bills_path %>
        <ul class="menu vertical">
          <li><%= link_to "Create", new_bill_path %></li>
          <li><%= link_to "All Bills", bills_path %></li>
        </ul>
      </li>
      <li>
        <%= link_to "Savings", savings_path %>
        <ul class="menu vertical">
          <li><%= link_to "Create", new_saving_path %></li>
          <li><%= link_to "All Savings", savings_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_savings.html.erb
<% if month.savings.empty? %>
<h3>
  No Savings For This Month
</h3>
<% else %>
<div class="table-scroll grid-x align-center">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Amount</th>
      <th>Percentage</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% month.savings.order(:name).each do |saving| %>
      <tr>
        <td><%= saving.name %></td>
        <td><%= saving.category %></td>
        <td><%= '%.2f' % saving.amount %></td>
        <td><%= get_single_percentage(month, saving.amount) %></td>
        <td><%= link_to 'Edit', edit_saving_path(saving) %></td>
        <td><%= link_to 'Destroy', saving, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    <tr>
      <th>TOTAL:</th>
      <th></th>
      <th><%= '%.2f' % month.savings.sum(&:amount) %></th>
      <th><%= get_total_percentage(month, 'savings') %></th>
      <th><%= link_to 'Add', new_saving_path %></th>
      <th><%= link_to 'See All', savings_path %></th>
    </tr>
  </tbody>
</table>
</div>
<% end %>
<div class="grid-x align-center grid-margin-x" style="text-align: center;">
  <div class="cell small-3">
    <%= link_to "Add A Saving", new_saving_path, {class: "button small", style: "color: white;"} %>
  </div>
  <div class="cell small-3">
    <%= link_to "See All Savings", savings_path, {class: "button small", style: "color: white;"} %>
  </div>
</div>

app/views/layouts/_spendings.html.erb
  <div class="table-scroll grid-x align-center">
    <table>
      <thead>
      <tr>
        <th>Total: <%= '%.2f' % month.spending_amount %> | <%= get_total_percentage(month, 'spendings') %></th>
      </tr>
      <tbody>
      <tr>
        <td>Amount Per Week (4 Weeks): <%= '%.2f' % (month.spending_amount / 4) %></td>
      </tr>
      <tr>
        <td>Amount Per Week (5 Weeks): <%= '%.2f' % (month.spending_amount / 5) %></td>
      </tr>
      <tr>
        <td><%= link_to 'Edit Spending Amount', edit_month_path(month.id), {class: "button small", style: "color: white;"} %></td>
      </tr>
      </tbody>
    </table>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Easy Budget" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <nav>
    <%= render 'layouts/nav' %>  
  </nav>

  <body style="min-height: calc(100vh - 60px); padding-bottom: 60px; position: relative;">

    <%= yield %>
    
    <%= render 'layouts/footer' %>
  </body>
  

</html>